services:

  api1:
    container_name: api1
    image: gasparbarancelli/rinha-backend-2024:latest
    environment:
      - DATABASE_HOSTNAME=db
      - QUARKUS_HTTP_PORT=8081
    ports:
      - '8081:8081'
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "125MB"
    logging:
      driver: none
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  api2:
    container_name: api2
    image: gasparbarancelli/rinha-backend-2024:latest
    environment:
      - DATABASE_HOSTNAME=db
      - QUARKUS_HTTP_PORT=8082
    ports:
      - '8082:8082'
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "125MB"
    logging:
      driver: none
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  envoy:
    container_name: envoy
    image: envoyproxy/envoy:v1.20.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    logging:
      driver: none
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]

  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=backend
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha-backend
    ports:
      - '5432:5432'
    command: ["postgres", "-c", "logging_collector=false", "-c", "max_connections=30"]
    volumes:
      - ./import.sql:/docker-entrypoint-initdb.d/script.sql
    logging:
      driver: none
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "200MB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s