services:

  api1:
    container_name: api1
    image: gasparbarancelli/rinha-2024-java-nativo-22:latest
    network_mode: host
    environment:
      - HTTP_PORT=8081
      - CREATE_DATABASE=true
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "100MB"

  api2:
    container_name: api2
    image: gasparbarancelli/rinha-2024-java-nativo-22:latest
    network_mode: host
    environment:
      - HTTP_PORT=8082
      - CREATE_DATABASE=false
    depends_on:
      - api1
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "100MB"

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  db:
    image: cockroachdb/cockroach:latest
    command: start-single-node
    environment:
      - COCKROACH_DATABASE=rinha
      - COCKROACH_USER=rinha
      - COCKROACH_PASSWORD=backend
    network_mode: host
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health?ready=1" ]
      interval: 3s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "300MB"
