services:

  api1:
    container_name: api1
    image: gasparbarancelli/rinha-2024-java-nativo-22:latest
    network_mode: host
    environment:
      - HTTP_PORT=8081
      - CREATE_DATABASE=true
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "100MB"

  api2:
    container_name: api2
    image: gasparbarancelli/rinha-2024-java-nativo-22:latest
    network_mode: host
    environment:
      - HTTP_PORT=8082
      - CREATE_DATABASE=false
    depends_on:
      - api1
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "100MB"

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: backend
      MYSQL_DATABASE: rinha
      MYSQL_USER: rinha
      MYSQL_PASSWORD: backend
    network_mode: host
    volumes:
      - ./import.sql:/docker-entrypoint-initdb.d/import.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "300MB"

