version: '3'

services:

  api1:
    container_name: api1
    image: gasparbarancelli/rinha-backend-2024:latest
    environment:
      - DATABASE_HOSTNAME=db
      - QUARKUS_HTTP_PORT=8081
    ports:
      - '8081:8081'
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  api2:
    container_name: api2
    image: gasparbarancelli/rinha-backend-2024:latest
    environment:
      - DATABASE_HOSTNAME=db
      - QUARKUS_HTTP_PORT=8082
    ports:
      - '8082:8082'
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '9999:9999'
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  # sim, a senha esta root e aporta esta como default :P
  # nao facam isso em producao rsrs
  db:
    container_name: db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RINHA_BACKEND
      MYSQL_USER: rinha
      MYSQL_PASSWORD: backend
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - './data:/docker-entrypoint-initdb.d'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10