services:

  api1:
    container_name: api1
    image: gasparbarancelli/rinha-backend-2024:latest
    environment:
      - DATABASE_HOSTNAME=db
      - QUARKUS_HTTP_PORT=8081
    ports:
      - '8081:8081'
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "125MB"

  api2:
    container_name: api2
    image: gasparbarancelli/rinha-backend-2024:latest
    environment:
      - DATABASE_HOSTNAME=db
      - QUARKUS_HTTP_PORT=8082
    ports:
      - '8082:8082'
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "125MB"

  envoy:
    container_name: envoy
    image: envoyproxy/envoy:v1.20.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]


  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass rinhaBackend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=backend
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha-backend
    ports:
      - '5432:5432'
    command: 'postgres -c max_connections=1000 -c shared_buffers=128MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    volumes:
      - ./import.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
