services:

  api1:
    container_name: api1
    image: gasparbarancelli/rinha-backend-2024-h2:latest
    environment:
      - DATABASE_HOSTNAME=db
      - QUARKUS_HTTP_PORT=8081
    ports:
      - '8081:8081'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  api2:
    container_name: api2
    image: gasparbarancelli/rinha-backend-2024-h2:latest
    environment:
      - DATABASE_HOSTNAME=db
      - QUARKUS_HTTP_PORT=8082
    ports:
      - '8082:8082'
    depends_on:
      - api1
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  envoy:
    container_name: envoy
    image: envoyproxy/envoy:v1.20.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]

  db:
    container_name: db
    image: gasparbarancelli/rinha-backend-database:latest
    ports:
      - '9092:9092'
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "250MB"