CREATE DATABASE rinha-backend;

CREATE TABLE CLIENTE (
     ID INT AUTO_INCREMENT PRIMARY KEY,
     LIMITE INT,
     SALDO INT DEFAULT 0
);

CREATE TABLE TRANSACAO (
       ID INT AUTO_INCREMENT PRIMARY KEY,
       CLIENTE_ID INT NOT NULL,
       VALOR INT NOT NULL,
       TIPO CHAR(1) NOT NULL,
       DESCRICAO VARCHAR(10) NOT NULL,
       DATA TIMESTAMP NOT NULL,
       FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE INDEX TRANSACAO_DATA_IDX ON TRANSACAO (DATA DESC);

-- As inserções de dados podem permanecer as mesmas, sem alterações necessárias
INSERT INTO CLIENTE (ID, LIMITE)
VALUES (1, 100000),
       (2, 80000),
       (3, 1000000),
       (4, 10000000),
       (5, 500000);