CREATE TABLE CLIENTE (
     ID INT PRIMARY KEY,
     LIMITE INT NOT NULL,
     SALDO INT NOT NULL DEFAULT 0
) ENGINE=MyISAM;

CREATE TABLE TRANSACAO (
     ID INT AUTO_INCREMENT PRIMARY KEY,
     CLIENTE_ID INT NOT NULL,
     VALOR INT NOT NULL,
     TIPO CHAR(1) NOT NULL,
     DESCRICAO VARCHAR(10) NOT NULL,
     DATA TIMESTAMP NOT NULL
) ENGINE=MyISAM;

CREATE INDEX IDX_TRANSACAO_CLIENTE ON TRANSACAO (CLIENTE_ID);

INSERT INTO CLIENTE (ID, LIMITE)
VALUES (1, 100000),
       (2, 80000),
       (3, 1000000),
       (4, 10000000),
       (5, 500000);